post http://localhost:3000/api/dispositivos
content-type: application/json

{
  "id" : 2,
  "nome": "arduino",
  "modelo": "uno",
  "descricao": "Placa Arduino Uno",
  "status": "inativo"
}

###

get http://localhost:3000/api/dispositivos/

###

post http://localhost:3000/api/dispositivos/
content-type: application/json

{
  "usuario_id": 1,
  "nome": "usd",
  "descricao": "Placa Arduino Uno",
  "criado_em": "2025-06-15T21:34:00.000Z"
}
###

delete http://localhost:3000/api/dispositivos/2
